Bimotor\MainBundle\Entity\User:
    repositoryClass: Bimotor\MainBundle\Repository\UserRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        image:
            type: string
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
        preUpdate: [setUpdatedAtValue]